---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## R Setup for knitr
```{R}
library(knitr)
opts_chunk$set(echo = TRUE)
```

## Load required libraries
```{R}
library(dplyr)
library(lubridate)
library(ggplot2)
```

## Loading and preprocessing the data

Data is loaded using read.csv()
Data file is already downloaded and saved under data/ folder 
within the current working directory.

```{R}
activityData <- read.csv(".\\data\\activity.csv"
                         , header=TRUE
                         , colClasses=c("numeric", "character", "integer"))
```

## Check and change data formats, if required.

Check data structure and sample
```{R}
str(activityData)
head(activityData)
summary(activityData)
```

We see that there are missing values in "steps" 
and date is of format yyyy-mm-dd

## Data Transformation and Processing 

Set "date" to proper date format using lubridate
```{R}
activityData$date <- ymd(activityData$date)
```

## What is mean total number of steps taken per day?

Calculate Steps per Day
```{R}
dsteps <- activityData %>%
  filter(!is.na(steps)) %>%
  group_by(date) %>%
  summarize(dsteps = sum(steps)) %>%
  print

```

Calculate Mean and Median steps per day

```{R}
steps_mean    <- mean(dsteps$dsteps, na.rm = TRUE)
steps_median <- median(dsteps$dsteps, na.rm = TRUE)

steps_mean
steps_median
```

Mean of total steps per day   : `r as.character.numeric_version(steps_mean)`

Median of total steps per day : `r as.character.numeric_version(steps_median)`

1. Plot histogram of steps per day

```{R}
ggplot(dsteps, aes(x = dsteps)) +
  geom_histogram( fill="blue", binwidth=1000) +
  labs(title = "Histogram of Steps per day", x = "Steps per day", y = "Frequency")

```



## What is the average daily activity pattern?

Calculate average steps taken in each 5-min interval per day.

```{R}
intervals <- activityData %>%
  filter(!is.na(steps))   %>%
  group_by(interval)      %>%
  summarize(steps = mean(steps))

```

1. Time series plot of the 5 min interval and average number of steps
across all days

We will use plot to make this time series plot
```{R}
plot(intervals$interval
    ,intervals$steps
    ,type="l"
    ,col="red"
    ,xlab = "Interval", ylab="Steps"
    ,main="Average Steps per 5 min Interval")

```

2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

This can be calculated using which.max()

```{R}
maxstepInt <-intervals[which.max(intervals$steps),]

```
Max Steps (average) in an Interval : `r as.character.numeric_version(round(maxstepInt$steps))`

Interval with max Steps (average)  : `r as.character.numeric_version(maxstepInt$interval)`


## Imputing missing values
1. Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
```{R}
countMissingValues <- sum(is.na(activityData$steps))
```
Count of missing values : `r as.character.numeric_version(countMissingValues)`

2. Devise a strategy for filling in all of the missing values in the dataset
We will use the average steps for a given interval to fill in missing steps

3. Create a new dataset that is equal to the original dataset but with the missing data filled in with average steps for that interval

```{R}
activityData2 <- activityData
missingVals <- is.na(activityData$steps)
avgSteps <- tapply(activityData2$steps, activityData2$interval
                       ,mean
                       ,na.rm=TRUE
                       ,simplify=TRUE
                      )
activityData2$steps[missingVals] <- avgSteps[as.character( 
                                       activityData2$interval[missingVals]
                                       )]
```

Check for missing values in the original and new datasets
```{R}
countMissingValues  <- sum(is.na(activityData$steps))
countMissingValues2 <- sum(is.na(activityData2$steps))
```

Missing values in original dataset: `r as.character.numeric_version(countMissingValues)`

Missing values in new dataset     : `r as.character.numeric_version(countMissingValues2)`

4. Histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day

Calculate Steps per Day using imputed dataset
```{R}
dsteps2 <- activityData2 %>%
  filter(!is.na(steps)) %>%
  group_by(date) %>%
  summarize(dsteps = sum(steps)) %>%
  print

```
Calculate Mean and Median steps per day using the new dataset

```{R}
steps_mean2    <- mean(dsteps2$dsteps, na.rm = TRUE)
steps_median2 <- median(dsteps2$dsteps, na.rm = TRUE)

steps_mean2
steps_median2
```

Mean of total steps per day   : `r as.character.numeric_version(steps_mean2)`

Median of total steps per day : `r as.character.numeric_version(steps_median2)`

*We see that the the mean and median are same with imputed missing values dataset*


Plot Histogram
```{R}
ggplot(dsteps2, aes(x = dsteps)) +
  geom_histogram( fill="blue", binwidth=1000) +
  labs(title = "Histogram of Steps per day", x = "Steps per day", y = "Frequency")

```



## Are there differences in activity patterns between weekdays and weekends?

1. Create a new factor variable in the dataset with two levels - "weekday" and "weekend" indicating whether a given date is a weekday or weekend day

We will create a new column using mutate function from dplyr

```{R}
activityData2 <- mutate(activityData2
                      ,weektype = ifelse(weekdays(as.POSIXlt(activityData2$date)) 
                                          %in% c("Saturday", "Sunday")
                                         , "weekend", "weekday"
                                         )
                       )

```

2. Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken

```{R}
intervalWeektype <- activityData2 %>% 
       group_by(interval, weektype) %>%
       summarise(steps = mean(steps))

     
```       

Panel Plot
```{R}
p <- ggplot(intervalWeektype
            ,aes(x = interval
                ,y = steps
                ,color = weektype
                )
            ) +
  xlab("interval") +
  ylab("Number of steps") +
  geom_line() +
  facet_wrap(~weektype, ncol = 1, nrow=2)
print(p)
```
